### ISSUE TITLE
Release v0.6

### ISSUE THREAD

**Issue by SunDoge** [SunDoge/typed-args#11]
# Roadmap

## v0.6.0

- [x] ~~Rename API to `from_args`, `from_known_args`~~

## v0.6.1

- [ ] Write doc for how to use `add_argument_group` and `add_subparsers`
- [x] Add typings to `add_argument`, `add_argument_group`, `add_subparsers` and `add_parser`
